---
name: Build Tishy Kernel

on:
  push:
    branches:
      - main
    tags:
      - "*-frl*"
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  attestations: write
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build_kernel:
    strategy:
      fail-fast: false
      matrix:
        arch: ["x86_64"]
        fedora_version: [43]
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Build Environment
        run: |
          FEDORA_VERSION="${{ matrix.fedora_version }}"
          sudo podman build . --tag 'fedora_builder' \
            --build-arg UID=$(id -u) --build-arg GID=$(id -g) \
            --build-arg FEDORA_VERSION=${FEDORA_VERSION:-43}
          sudo podman image prune -f

      - name: Maximize build space
        run: |
          df -h
          sudo swapoff -a; sudo rm -f /swapfile
          shopt -s nullglob
          printf '%s\0' /opt/PyPy /opt/az /opt/node/ /opt/pipx /opt/go /opt/Ruby \
              /usr/lib/llvm-* /usr/local/julia* /usr/local/lib/android /usr/share/dotnet \
              /usr/share/swift /usr/local/.ghcup /usr/lib/firefox /opt/google/chrome \
              /opt/microsoft/msedge \
              | sudo xargs -0 -n1 -P4 rm -rf
          df -h

      - name: Compile Kernel
        run: |
          CCACHE_USE=0
          sudo podman run --rm -v $(pwd):/workspace -e UID=$UID -e GID=$GID \
              -e ARCH=${{ matrix.arch }} -e FEDORA_VERSION=${{ matrix.fedora_version }} \
              --env CCACHE_USE="$CCACHE_USE" \
              fedora_builder bash ./build.sh \
              | grep -v ".o: warning: objtool:"

          rm -rf ./certs

      - name: Separate debuginfo into different folder
        run: |
          mkdir -p ./build/DRPMS/
          mv ./build/RPMS/${{ matrix.arch }}/kernel-debuginfo-*.rpm ./build/DRPMS/

      - name: Upload Kernel to action
        uses: actions/upload-artifact@v4
        with:
          name: kernel-f${{ matrix.fedora_version}}-${{ matrix.arch }}
          path: |
            ./build/RPMS/${{ matrix.arch }}/kernel-*.rpm
          compression-level: 7

      - name: Upload Kernel debuginfo to action
        uses: actions/upload-artifact@v4
        with:
          name: kernel-f${{ matrix.fedora_version}}-${{ matrix.arch }}-debuginfo
          path: |
            ./build/DRPMS/*.rpm
          compression-level: 7

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: |
            ./build/RPMS/${{ matrix.arch }}/kernel-*.rpm

      - name: Create OCI image
        id: oci
        run: |
            FEDORA_VERSION="${{ matrix.fedora_version }}" ARCH="${{ matrix.arch }}" \
              buildah unshare ./oci.sh

      - name: Upload OCI image to Registry
        id: upload
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin
          podman push --digestfile .oci-digest "localhost/kernel-f${{ matrix.fedora_version}}" \
            "docker://ghcr.io/${{ github.repository }}:${{ github.ref_name }}-f${{ matrix.fedora_version }}-${{ matrix.arch }}"
          echo "digest=$(cat .oci-digest)" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate OCI attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-digest: "${{ steps.upload.outputs.digest }}"
          subject-name: "ghcr.io/${{ github.repository }}"
          push-to-registry: true

      - name: Upload OCI image to latest
        if: github.ref_type == 'tag' && contains(github.ref_name, '-frl')
        run: |
          podman push "localhost/kernel-f${{ matrix.fedora_version}}" \
            "docker://ghcr.io/${{ github.repository }}:latest-f${{ matrix.fedora_version }}-${{ matrix.arch }}"

      - name: Upload Kernel to release
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ./build/RPMS/${{ matrix.arch }}/kernel-*.rpm
          fail_on_unmatched_files: false
          draft: true

  post_release:
    runs-on: ubuntu-24.04
    needs: build_kernel
    if: github.ref_type == 'tag'
    steps:
      - name: Make release latest
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
