name: Build Bazzite Kernel

on:
  workflow_dispatch:
    inputs:
      arm:
        description: "Build arm version only"
        type: boolean
        default: false
  release:
    types: [published]
  push:
    branches:
      - bazzite-*

permissions:
  contents: write

jobs:
  build_kernel:
    environment: prod
    strategy:
      fail-fast: false
      matrix:
        arch: ${{ github.event.inputs.arm == 'true' && fromJSON('["aarch64"]') || fromJSON('["aarch64", "x86_64"]') }}
        fedora_version: [42, 43]
        # exclude:
        #   - arch: aarch64
        #     fedora_version: 41
    runs-on: ${{ matrix.arch == 'aarch64' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}

    steps:
      - name: Maximize build space
        uses: ublue-os/remove-unwanted-software@v9

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Build Environment
        run: |
          FEDORA_VERSION="${{ matrix.fedora_version }}"
          sudo podman build . --tag 'fedora_builder' \
            --build-arg UID=$(id -u) --build-arg GID=$(id -g) \
            --build-arg FEDORA_VERSION=${FEDORA_VERSION:-41}

      - name: Fixup kernel source
        run: |
          # Get the tarfile_release value from the spec file and download it
          TARFILE_RELEASE=$(sed -n 's/^%define[[:space:]]\+tarfile_release[[:space:]]\+//p' kernel.spec)
          NVIDIA_RELEASE=$(sed -n 's/^%define[[:space:]]\+nvidia_version[[:space:]]\+//p' kernel.spec)
          NVIDIA_RELEASE_LTS=$(sed -n 's/^%define[[:space:]]\+nvidia_version_lts[[:space:]]\+//p' kernel.spec)
          ZFS_RELEASE=$(sed -n 's/^%define[[:space:]]\+zfs_version[[:space:]]\+//p' kernel.spec)

          echo "TARFILE_RELEASE is $TARFILE_RELEASE"
          echo "NVIDIA_RELEASE is $NVIDIA_RELEASE"
          echo "NVIDIA_RELEASE_LTS is $NVIDIA_RELEASE_LTS"
          echo "ZFS_RELEASE is $ZFS_RELEASE"

          curl -L -o "linux-${TARFILE_RELEASE}.tar.xz" "https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-${TARFILE_RELEASE}.tar.xz"
          curl -L -o "NVIDIA-Linux-${{ matrix.arch }}-${NVIDIA_RELEASE}.run" \
            "https://download.nvidia.com/XFree86/Linux-${{ matrix.arch }}/${NVIDIA_RELEASE}/NVIDIA-Linux-${{ matrix.arch }}-${NVIDIA_RELEASE}.run"
          if [ "$NVIDIA_RELEASE" != "$NVIDIA_RELEASE_LTS" ]; then
            echo "Also downloading LTS version of NVIDIA driver $NVIDIA_RELEASE_LTS"
            curl -L -o "NVIDIA-Linux-${{ matrix.arch }}-${NVIDIA_RELEASE}.run" \
              "https://download.nvidia.com/XFree86/Linux-${{ matrix.arch }}/${NVIDIA_RELEASE_LTS}/NVIDIA-Linux-${{ matrix.arch }}-${NVIDIA_RELEASE_LTS}.run"
          fi
          curl -L -o "zfs-${ZFS_RELEASE}.tar.gz" \
            "https://github.com/openzfs/zfs/releases/download/zfs-${ZFS_RELEASE}/zfs-${ZFS_RELEASE}.tar.gz"

      - name: Load Universal Blue Keys
        if: github.event_name == 'release' && matrix.arch == 'x86_64'
        env:
          UBLUE_MOKKEY_LEGACY: ${{ secrets.UBLUE_MOKKEY_LEGACY }}
          UBLUE_MOKKEY_KERNEL: ${{ secrets.UBLUE_MOKKEY_KERNEL }}
        run: |
          mkdir -p certs
          echo "${UBLUE_MOKKEY_LEGACY}" > certs/ubmok101.priv
          cp ubmok101.cer certs/ubmok101.der
          echo "${UBLUE_MOKKEY_KERNEL}" > certs/ubmok102.priv
          cp ubmok102.cer certs/ubmok102.der

      - name: Setup Secure Boot
        run: |
          sudo apt-get install efitools -y
          ./create_sign.sh

      - name: Compile Kernel
        run: |
          FEDORA_VERSION="${{ matrix.fedora_version }}"
          ARCH="${{ matrix.arch }}"
          sudo podman run --rm -v $(pwd):/workspace $DISABLE_ARG \
            -v $(pwd)/certs/pki/ubluesign:/etc/pki/pesign \
            fedora_builder fedpkg \
            --name kernel --namespace rpms --release "f${FEDORA_VERSION:-41}" \
            local --arch ${ARCH:-x86_64} --with bazzite --with nvidia --with zfs \
            --with ubsb --builddir build --buildrootdir buildroot \
             | grep -v "nvidia.o: warning: objtool:"

          # We are signed, remove certs
          rm -rf ./certs

      - name: Separate debuginfo into different folder
        run: |
          mkdir -p debuginfo
          mv ${{ matrix.arch }}/kernel-debuginfo-*.rpm debuginfo/

      - name: Upload Kernel to action
        uses: actions/upload-artifact@v4
        with:
          name: kernel-f${{ matrix.fedora_version}}-${{ matrix.arch }}
          path: |
            .build-*.log
            ${{ matrix.arch }}/kernel-*.rpm
          compression-level: 7

      - name: Upload Kernel debuginfo to action
        uses: actions/upload-artifact@v4
        with:
          name: kernel-f${{ matrix.fedora_version}}-${{ matrix.arch }}-debuginfo
          path: |
            .build-*.log
            debuginfo/*.rpm
          compression-level: 7

      - name: Convert to Arch
        if: matrix.arch == 'x86_64' && matrix.fedora_version == 43 #arch_fedora
        run: |
          # Grab kernel ver from the log
          KERNEL_VER=$(ls -a | grep .build | head -n 1 | sed 's/.build-//' | sed 's/.log//')
          ARCH_VER=$(echo $KERNEL_VER | sed 's/-/./g')
          # Place in PKGBUILD
          cat PKGBUILD-ACTION | \
            sed "s/VERSION_FEDORA/${KERNEL_VER}.x86_64/" | \
            sed "s/VERSION_TAG/${ARCH_VER}/" \
            > x86_64/PKGBUILD
          sudo podman build . -f Dockerfile-arch --tag 'arch_builder' --build-arg UID=$(id -u) --build-arg GID=$(id -g) 
          sudo podman run --rm -v $(pwd)/x86_64:/workspace arch_builder makepkg -s

      - name: Upload Kernel arch package to action
        uses: actions/upload-artifact@v4
        if: matrix.arch == 'x86_64' && matrix.fedora_version == 43 #arch_fedora
        with:
          name: linux-f${{ matrix.fedora_version }}-arch
          path: |
            x86_64/linux-*.pkg.tar.zst
          compression-level: 7

      - name: Upload Kernel to release
        if: github.event_name == 'release'
        uses: Wandalen/wretry.action@v3.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          attempt_limit: 3
          attempt_delay: 15000
          action: softprops/action-gh-release@v2
          with: |
            files: |
              ${{ matrix.arch }}/kernel-*.rpm
              x86_64/linux-*.pkg.tar.zst
              x86_64/linux-*.pkg.tar.zst.sig
            fail_on_unmatched_files: false
            make_latest: false

  # Trigger ublue-os/akmods build/kernel cache
  post_release:
    runs-on: ubuntu-24.04
    needs: build_kernel
    if: github.event_name == 'release'
    steps:
      - name: Make release latest
        if: github.event.release.prerelease == false
        uses: Wandalen/wretry.action@v3.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          attempt_limit: 3
          attempt_delay: 15000
          action: softprops/action-gh-release@v2
          with: |
            make_latest: true

  update_aur:
    uses: ./.github/workflows/publish-aur.yml
    needs: build_kernel
    secrets: inherit
    if: github.event_name == 'release' && github.event.release.prerelease == false
    with:
      relver: ${{ github.event.release.tag_name }}
      fedora_version: 42 #arch_fedora
