name: Build Bazzite Kernel

on:
  release:
    types: [published]
  push:
    branches:
      - bazzite-*

permissions:
  contents: write

concurrency:
  # Group by commit hash so that
  # the release cancels the push
  group: ${{ github.sha }}
  cancel-in-progress: true

jobs:
  build_kernel:
    environment: prod
    strategy:
      fail-fast: false
      matrix:
        arch: ["aarch64", "x86_64"]
        fedora_version: [43]
    runs-on: ${{ matrix.arch == 'aarch64' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Build Environment
        run: |
          FEDORA_VERSION="${{ matrix.fedora_version }}"
          sudo podman build . --tag 'fedora_builder' \
            --build-arg UID=$(id -u) --build-arg GID=$(id -g) \
            --build-arg FEDORA_VERSION=${FEDORA_VERSION:-41}

      - name: Load Universal Blue Keys
        if: github.event_name == 'release' && matrix.arch == 'x86_64'
        env:
          UBLUE_MOKKEY_LEGACY: ${{ secrets.UBLUE_MOKKEY_LEGACY }}
          UBLUE_MOKKEY_KERNEL: ${{ secrets.UBLUE_MOKKEY_KERNEL }}
        run: |
          mkdir -p certs
          if [ -n "$UBLUE_MOKKEY_LEGACY" ] && [ -n "$UBLUE_MOKKEY_KERNEL" ]; then
            echo "${UBLUE_MOKKEY_LEGACY}" > certs/ubmok101.priv
            cp ubmok101.cer certs/ubmok101.der
            echo "${UBLUE_MOKKEY_KERNEL}" > certs/ubmok102.priv
            cp ubmok102.cer certs/ubmok102.der
          else
            echo "One or more keys are missing, setup will create temporary keys"
          fi

      - name: Maximize build space
        run: |
          df -h
          #  remove swapfile (3gb)
          sudo swapoff -a; sudo rm -f /swapfile
          # Remove toolchains, browsers
          shopt -s nullglob
          printf '%s\0' /opt/PyPy /opt/az /opt/node/ /opt/pipx /opt/go /opt/Ruby \
              /usr/lib/llvm-* /usr/local/julia* /usr/local/lib/android /usr/share/dotnet \
              /usr/share/swift /usr/local/.ghcup /usr/lib/firefox /opt/google/chrome \
              /opt/microsoft/msedge /usr/share/miniconda /opt/hostedtoolcache \
              | sudo xargs -0 -n1 -P8 rm -rf
          df -h

      - name: Compile Kernel
        run: |
          sudo FEDORA_VERSION="${{ matrix.fedora_version }}" ARCH="${{ matrix.arch }}" \
            podman run --rm -v $(pwd):/workspace -e UID=$UID -e GID=$GID \
              fedora_builder bash ./build.sh \
              | grep -v ".o: warning: objtool:"

          # We are signed, remove certs
          rm -rf ./certs

      - name: Separate debuginfo into different folder
        run: |
          mkdir -p ./build/DRPMS/
          mv ./build/RPMS/${{ matrix.arch }}/kernel-debuginfo-*.rpm ./build/DRPMS/

      - name: Upload Kernel to action
        uses: actions/upload-artifact@v4
        with:
          name: kernel-f${{ matrix.fedora_version}}-${{ matrix.arch }}
          path: |
            ./build/RPMS/${{ matrix.arch }}/kernel-*.rpm
          compression-level: 7

      - name: Upload Kernel debuginfo to action
        uses: actions/upload-artifact@v4
        with:
          name: kernel-f${{ matrix.fedora_version}}-${{ matrix.arch }}-debuginfo
          path: |
            ./build/DRPMS/*.rpm
          compression-level: 7

      - name: Convert to Arch
        if: matrix.arch == 'x86_64' && matrix.fedora_version == 43 #arch_fedora
        run: |
          # Grab kernel ver from the log
          KERNEL_VER=$(ls -a build/SRPMS/ | grep "kernel-*" | head -n 1 | sed 's/^kernel-//' | sed 's/.src.rpm//')
          ARCH_VER=$(echo $KERNEL_VER | sed 's/-/./g')
          # Place in PKGBUILD
          cat PKGBUILD-ACTION | \
            sed "s/VERSION_FEDORA/${KERNEL_VER}.x86_64/" | \
            sed "s/VERSION_TAG/${ARCH_VER}/" \
            > ./build/RPMS/${{ matrix.arch }}/PKGBUILD
          sudo podman build . -f Dockerfile-arch --tag 'arch_builder' --build-arg UID=$(id -u) --build-arg GID=$(id -g) 
          sudo podman run --rm -v $(pwd)/build/RPMS/${{ matrix.arch }}/:/workspace arch_builder makepkg -s

      - name: Upload Kernel arch package to action
        uses: actions/upload-artifact@v4
        if: matrix.arch == 'x86_64' && matrix.fedora_version == 43 #arch_fedora
        with:
          name: linux-f${{ matrix.fedora_version }}-arch
          path: |
            ./build/RPMS/${{ matrix.arch }}/linux-*.pkg.tar.zst
          compression-level: 7

      - name: Upload Kernel to release
        if: github.event_name == 'release'
        uses: Wandalen/wretry.action@v3.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          attempt_limit: 3
          attempt_delay: 15000
          action: softprops/action-gh-release@v2
          with: |
            files: |
              ./build/RPMS/${{ matrix.arch }}/kernel-*.rpm
              ./build/SRPMS/${{ matrix.arch }}/kernel-*.rpm
              ./build/RPMS/${{ matrix.arch }}/linux-*.pkg.tar.zst
              ./build/RPMS/${{ matrix.arch }}/linux-*.pkg.tar.zst.sig
            fail_on_unmatched_files: false
            make_latest: false

  # Trigger ublue-os/akmods build/kernel cache
  post_release:
    runs-on: ubuntu-24.04
    needs: build_kernel
    if: github.event_name == 'release'
    steps:
      - name: Make release latest
        if: github.event.release.prerelease == false
        uses: Wandalen/wretry.action@v3.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          attempt_limit: 3
          attempt_delay: 15000
          action: softprops/action-gh-release@v2
          with: |
            make_latest: true

  update_aur:
    uses: ./.github/workflows/publish-aur.yml
    needs: build_kernel
    secrets: inherit
    if: github.event_name == 'release' && github.event.release.prerelease == false
    with:
      relver: ${{ github.event.release.tag_name }}
      fedora_version: 42 #arch_fedora
